<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="eminezeynep" failures="1" tests="6" name="Regression Test" time="128.125" errors="0" timestamp="2023-02-10T23:08:26 EST">
  <testcase classname="com.neotech.testcases.AddEmployeeTest" name="addEmployee" time="34.916"/>
  <testcase classname="com.neotech.testcases.AddEmployeeTest" name="addEmployee" time="35.742"/>
  <testcase classname="com.neotech.testcases.AddEmployeeTest" name="addEmployee" time="30.35"/>
  <testcase classname="com.neotech.testcases.LoginTest" name="emptyPasswordLogin" time="2.25"/>
  <testcase classname="com.neotech.testcases.LoginTest" name="invalidPasswordLogin" time="4.7">
    <failure type="java.lang.AssertionError" message="Error message does NOT match! expected [Invalid Credentials - bla bla bla] but found [Invalid Credentials]">
      <![CDATA[java.lang.AssertionError: Error message does NOT match! expected [Invalid Credentials - bla bla bla] but found [Invalid Credentials]
at com.neotech.testcases.LoginTest.invalidPasswordLogin(LoginTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- invalidPasswordLogin -->
  <testcase classname="com.neotech.testcases.LoginTest" name="validLogin" time="6.87"/>
  <testcase classname="com.neotech.testbase.BaseClass" name="@BeforeTest generateReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest generateReport -->
  <testcase classname="com.neotech.testbase.BaseClass" name="@AfterTest writeReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest writeReport -->
</testsuite> <!-- Regression Test -->
